services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    command: ["sh", "-e", "server_runner.sh"]
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
      - ./media:/app/media
    networks:
      - app-network

  nginx:
      image: nginx:1.29.2
      container_name: nginx-server
      ports:
        - "80:80"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        - ./staticfiles:/app/static
      restart: always
      networks:
        - app-network
      depends_on:
        - backend

networks:
  app-network:
    driver: bridge