# Generated by Django 5.2.7 on 2025-10-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThermalExpansionCalculator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("L0", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("S0", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("V0", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("alpha", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("E", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("delta_T", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("delta_L", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("delta_S", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("delta_V", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("sigma", models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
            options={
                "verbose_name": "ThermalExpansionCalculator",
                "verbose_name_plural": "ThermalExpansionCalculators",
                "db_table": "calculator_thermal_expansion_calculator",
                "ordering": ["-id"],
            },
        ),
    ]
