# Generated by Django 5.2.7 on 2025-10-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thermalexpansioncalculator",
            name="E",
            field=models.DecimalField(decimal_places=15, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="thermalexpansioncalculator",
            name="L0",
            field=models.DecimalField(decimal_places=15, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="thermalexpansioncalculator",
            name="S0",
            field=models.DecimalField(decimal_places=15, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="thermalexpansioncalculator",
            name="V0",
            field=models.DecimalField(decimal_places=15, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="thermalexpansioncalculator",
            name="alpha",
            field=models.DecimalField(decimal_places=15, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="thermalexpansioncalculator",
            name="delta_L",
            field=models.DecimalField(decimal_places=15, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="thermalexpansioncalculator",
            name="delta_S",
            field=models.DecimalField(decimal_places=15, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="thermalexpansioncalculator",
            name="delta_T",
            field=models.DecimalField(decimal_places=15, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="thermalexpansioncalculator",
            name="delta_V",
            field=models.DecimalField(decimal_places=15, max_digits=1000),
        ),
        migrations.AlterField(
            model_name="thermalexpansioncalculator",
            name="sigma",
            field=models.DecimalField(decimal_places=15, max_digits=1000),
        ),
    ]
